### PR TITLE
Add issue template

### PR DESCRIPTION
**Pull request by SuperOP535**
Feel free to make it better :)

Sorry, it is 3 commits because I did some stuff wrong :/

### CODE REVIEW

**Comment by LeafHacker** [comment]
I made some changes to this PR @SuperOP535 . Are you happy with them? If so I'll squash merge this in your name.

**Comment by SuperOP535** [comment]
Sure, merge it when you want :)

**Comment by Thunder33345** [comment]
what about suggestion formats as issue tracker was used for suggestions too?

**Comment by LeafHacker** [comment]
Merged as https://github.com/ImpactDevelopment/ImpactClient/commit/d13d1e9639b594659ff88978fafee7707b12766b thanks

**Comment by LeafHacker** [comment]
@Thunder33345 see [Line 6](https://github.com/ImpactDevelopment/ImpactClient/blame/d13d1e9639b594659ff88978fafee7707b12766b/.github/ISSUE_TEMPLATE.md#L6)

**Comment by Thunder33345** [comment]
by that i mean like "if you are suggesting something, you should describe your suggestions and dont leave it blank" hopefully that can reduce asking questions back and forward and the "no details provided"
might not be as entirely necessary/needed

**Pull request merged**
